### ISSUE TITLE
Hello, I would like to add a new feature: downloading images with customizable sizes

### ISSUE THREAD

**Issue by rizkytegar** [ahmadammarm/image-generator#2]
Is this possible?

**Comment by ahmadammarm** [comment]
of course u can do it, just fork this repo and make a pull request to my repo

**Comment by ahmadammarm** [comment]
Sure u can contributing in this project, before that u must go to in this link [Getting Unsplash API Key](https://unsplash.com/developers). After u get the API Key u can fork this repository and put down ur API Key in ur .env file like this format
```
REACT_APP_UNSPLASH_CLIENT_ID=YOUR API KEY
```
After that u can implement it in ur local device and make the pull request to this repository
