### ISSUE TITLE
[Feature] random generate button  

### ISSUE THREAD

**Issue by nishaaannnt** [ahmadammarm/image-generator#8]
A button to get random image search for the user. 

Approach -

1. Make a array of different random keywords
2. Call a function on button click which uses random function to select one of the keywords

Assign it to me for HacktoberFest.

**Comment by ahmadammarm** [comment]
Sure u can contributing in this project, before that u must go to in this link [Getting Unsplash API Key](https://unsplash.com/developers). After u get the API Key u can fork this repository and put down ur API Key in ur .env file like this format
```
REACT_APP_UNSPLASH_CLIENT_ID=YOUR API KEY
```
After that u can implement it in ur local device and make the pull request to this repository
